services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nn0808764566
      MYSQL_DATABASE: shop
      MYSQL_USER: root
      MYSQL_PASSWORD: Nn0808764566
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Nn0808764566
    ports:
      - "8080:80"